export const QUERY_DOCUMENTS = 'QUERY_DOCUMENTS';
export const QUERY_DOCUMENTS_SUCCESS = 'QUERY_DOCUMENTS_SUCCESS';
export const QUERY_DOCUMENTS_ERROR = 'QUERY_DOCUMENTS_ERROR';
export const COLLAPSE_FOLDER = 'COLLAPSE_FOLDER';
export const COLLAPSE_ALL_FOLDER = 'COLLAPSE_ALL_FOLDER';
